### ISSUE TITLE
OS X Support?

### ISSUE THREAD

**Issue by aequasi** [leovoel/BeautifulDiscord#1]
Not sure if there is OS X support or not, but when i try to run this i get:

```
0: Found Discord Canary Helper
1: Found Discord Canary
Discord executable to use (number): 1
WARNING: app.asar not found
Traceback (most recent call last):
  File "/usr/local/bin/beautifuldiscord", line 9, in <module>
    load_entry_point('BeautifulDiscord==0.1.0', 'console_scripts', 'beautifuldiscord')()
  File "/usr/local/lib/python3.5/site-packages/beautifuldiscord/app.py", line 168, in main
    with open('./resources/app/cssInjection.js', 'w') as f:
FileNotFoundError: [Errno 2] No such file or directory: './resources/app/cssInjection.js'
```

**Comment by leovoel** [comment]
it couldn't extract `app.asar` so the `./resources/app/` dir doesn't exist...
can you check where that exists on OSX?

**Comment by leovoel** [comment]
@aequasi i don't use OSX so i can't test it, but #2 should fix this. can you test it?

`python3 -m pip install -U https://github.com/Rapptz/BeautifulDiscord/archive/osx.zip`

**Comment by aequasi** [comment]
Works!

**Comment by Rapptz** [comment]
Neat.
