### ISSUE TITLE
OSError when running the script

### ISSUE THREAD

**Issue by EEKIM10** [leovoel/BeautifulDiscord#100]
What the title says - upon trying to run the beautifuldiscord script, it provides the below traceback:
```python
C:\Users\samue>beautifuldiscord
Found DiscordPTB.exe under C:\Users\...\AppData\Local\DiscordPTB\app-1.0.1001
Traceback (most recent call last):
  File "c:\users\...\appdata\local\programs\python\python38-32\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\...\appdata\local\programs\python\python38-32\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\...\AppData\Local\Programs\Python\Python38-32\Scripts\beautifuldiscord.exe\__main__.py", line 7, in <module>
  File "c:\users\...\appdata\local\programs\python\python38-32\lib\site-packages\beautifuldiscord\app.py", line 237, in main
    os.chdir(discord.script_path)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\...\\AppData\\Roaming\\DiscordPTB\\1.0.1001\\modules\\discord_desktop_core'
````
All I am running is `beautifuldiscord`

I have tried re-installing and updating and it's still not working.
any help is appriciated!

**Comment by ranbeer2004** [comment]
It is happening to me as well and when I check out the path I don't even find modules folder under "1.0.1001" .Has something changed from discord's side?

**Comment by Rapptz** [comment]
This is fixed in the [`moved-modules`](https://github.com/leovoel/BeautifulDiscord/tree/moved-modules) branch. Please test it before I merge it into the master branch.

**Comment by EEKIM10** [comment]
Yep, this is working. Thank you.
