### ISSUE TITLE
Linux version can't revert, causing weird issues

### ISSUE THREAD

**Issue by ren4ph** [leovoel/BeautifulDiscord#101]
I installed it on linux and it worked fine until I tried to revert. here is the full error:
beautifuldiscord --revert
Found Discord under /opt/discord
Traceback (most recent call last):
  File "/home/ren4ph/.local/bin/beautifuldiscord", line 33, in <module>
    sys.exit(load_entry_point('BeautifulDiscord==0.1.1', 'console_scripts', 'beautifuldiscord')())
  File "/home/ren4ph/.local/lib/python3.9/site-packages/beautifuldiscord/app.py", line 241, in main
    discord.terminate()
  File "/home/ren4ph/.local/lib/python3.9/site-packages/beautifuldiscord/app.py", line 21, in terminate
    process.kill()
  File "/usr/lib/python3.9/site-packages/psutil/__init__.py", line 271, in wrapper
    raise NoSuchProcess(self.pid, self._name)
psutil.NoSuchProcess: psutil.NoSuchProcess process no longer exists (pid=444485)

I checked, and I do have psutil installed so I don't know what the problem could be.

**Comment by ren4ph** [comment]
Also, whenever discord is in focus, it seems to be really laggy. The typing is delayed and the mouse kinda jitters around. Don't know if this is related, but though Id tell you that as well.
