### ISSUE TITLE
Doesn't work on macOS when not installed in the Applications folder

### ISSUE THREAD

**Issue by Bond-009** [leovoel/BeautifulDiscord#22]
```
Found Discord under /Users/Bond/Documents/Bond/Applications/Discord.app/Contents/MacOS
Traceback (most recent call last):
  File "/usr/local/bin/beautifuldiscord", line 11, in <module>
    load_entry_point('BeautifulDiscord==0.1.0', 'console_scripts', 'beautifuldiscord')()
  File "/usr/local/lib/python3.6/site-packages/beautifuldiscord/app.py", line 126, in main
    os.chdir(discord.resources_path)
FileNotFoundError: [Errno 2] No such file or directory: '/Applications/Discord.app/Contents/Resources'
```
It finds Discord under `/Users/Bond/Documents/Bond/Applications/` and tries to edit it in `/Applications/`

**Comment by Rapptz** [comment]
I think it should be fixed in https://github.com/leovoel/BeautifulDiscord/commit/77e0f01784bc908f6b412680a955cc9e05ab71c0 let me know if it isn't.

**Comment by Bond-009** [comment]
It still fails.
```
Found Discord PTB under /Users/Bond/Documents/Bond/Applications/Discord PTB.app/Contents/MacOS
Traceback (most recent call last):
  File "/usr/local/bin/beautifuldiscord", line 11, in <module>
    load_entry_point('BeautifulDiscord==0.1.0', 'console_scripts', 'beautifuldiscord')()
  File "/usr/local/lib/python3.6/site-packages/beautifuldiscord/app.py", line 127, in main
    os.chdir(discord.resources_path)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/Bond/Documents/Bond/Applications/Discord PTB.app/Contents/MacOS/../../Resources'
```
