### ISSUE TITLE
Error when running

### ISSUE THREAD

**Issue by JarrColl** [leovoel/BeautifulDiscord#27]
`Found Discord under /usr/share/discord
Traceback (most recent call last):
  File "/home/x/.virtualenv/BeautifulDiscord/bin/beautifuldiscord", line 11, in <module>
    load_entry_point('BeautifulDiscord==0.1.0', 'console_scripts', 'beautifuldiscord')()
  File "/home/x/.virtualenv/BeautifulDiscord/lib/python3.5/site-packages/beautifuldiscord/app.py", line 143, in main
    if extract_asar():
  File "/home/x/.virtualenv/BeautifulDiscord/lib/python3.5/site-packages/beautifuldiscord/app.py", line 98, in extract_asar
    a.extract('./app')
  File "/home/x/.virtualenv/BeautifulDiscord/lib/python3.5/site-packages/beautifuldiscord/asar.py", line 276, in extract
    self._extract_directory('.', self.header['files'], path)
  File "/home/x/.virtualenv/BeautifulDiscord/lib/python3.5/site-packages/beautifuldiscord/asar.py", line 254, in _extract_directory
    os.makedirs(dest)
  File "/home/x/.virtualenv/BeautifulDiscord/lib/python3.5/os.py", line 231, in makedirs
    makedirs(head, mode, exist_ok)
  File "/home/x/.virtualenv/BeautifulDiscord/lib/python3.5/os.py", line 241, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: './app'`

### I am running linux mint, python 3.5.2 in a virtualenv

**Comment by Rapptz** [comment]
This should be fixed now since it doesn't require writing in any directory except writeable directories.
