### ISSUE TITLE
Can't install on Windows 

### ISSUE THREAD

**Issue by FactoDoesStuff** [leovoel/BeautifulDiscord#32]
When I try to install BeautifulDiscord, it gives me this error:

C:\Users\owner>py -m beautifuldiscord --css C:\CSS\lol.css
Traceback (most recent call last):
  File "C:\Users\owner\.windows-build-tools\python27\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Users\owner\.windows-build-tools\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Users\owner\.windows-build-tools\python27\lib\site-packages\beautifuldiscord\__main__.py", line 1, in <module>
    from beautifuldiscord.app import main
  File "C:\Users\owner\.windows-build-tools\python27\lib\site-packages\beautifuldiscord\app.py", line 11, in <module>
    from beautifuldiscord.asar import Asar
  File "C:\Users\owner\.windows-build-tools\python27\lib\site-packages\beautifuldiscord\asar.py", line 102
    nonlocal concatenated_files, offset
                              ^
SyntaxError: invalid syntax

**Comment by Rapptz** [comment]
This is a Python 3 project, not a Python 2.
