### ISSUE TITLE
psutil 5.4.0 support

### ISSUE THREAD

**Issue by XCanG** [leovoel/BeautifulDiscord#35]
Add support of latest version psutil.
```
Traceback (most recent call last):
  File "c:\python\python36\lib\site-packages\pkg_resources\__init__.py", line 664, in _build_master
    ws.require(__requires__)
  File "c:\python\python36\lib\site-packages\pkg_resources\__init__.py", line 981, in require
    needed = self.resolve(parse_requirements(requirements))
  File "c:\python\python36\lib\site-packages\pkg_resources\__init__.py", line 872, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (psutil 5.4.0 (c:\python\python36\lib\site-packages), Requirement.parse('psutil==5.1.0'), {'BeautifulDiscord'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python\Python36\Scripts\beautifuldiscord-script.py", line 6, in <module>
    from pkg_resources import load_entry_point
  File "c:\python\python36\lib\site-packages\pkg_resources\__init__.py", line 3142, in <module>
    @_call_aside
  File "c:\python\python36\lib\site-packages\pkg_resources\__init__.py", line 3126, in _call_aside
    f(*args, **kwargs)
  File "c:\python\python36\lib\site-packages\pkg_resources\__init__.py", line 3155, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "c:\python\python36\lib\site-packages\pkg_resources\__init__.py", line 666, in _build_master
    return cls._build_from_requirements(__requires__)
  File "c:\python\python36\lib\site-packages\pkg_resources\__init__.py", line 679, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "c:\python\python36\lib\site-packages\pkg_resources\__init__.py", line 867, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'psutil==5.1.0' distribution was not found and is required by BeautifulDiscord
```

**Comment by Rapptz** [comment]
`psutil` has been unpinned for 6 months now.
