### ISSUE TITLE
new Canary Update is not applying css

### ISSUE THREAD

**Issue by InkxtheSquid** [leovoel/BeautifulDiscord#36]
index.js is not in this anymore, so if anyone is having problems this needs to be fixed

**Comment by InkxtheSquid** [comment]
here's some traceback if that helps
```Found Discord Canary under /Applications/Discord Canary.app/Contents/MacOS
WARNING: app.asar not found
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/beautifuldiscord", line 11, in <module>
    load_entry_point('BeautifulDiscord==0.1.0', 'console_scripts', 'beautifuldiscord')()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/beautifuldiscord/app.py", line 233, in main
    with open('./app/index.js', 'r', encoding='utf-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: './app/index.js'```

**Comment by cloudrac3r** [comment]
I also have this issue. Linux Mint 18 here.

Process to reproduce: remove discord-canary from system, `sudo rm -rf /usr/share/discord-canary` to get back to a clean slate. Then install the latest Canary 0.0.35, start it, quit it, `sudo chown -R cloud:cloud /usr/share/discord-canary` (so I have permission to modify its files), start it, then attempt to use BD.

    cloud@CloudPuter:~/Software/BeautifulDiscord$ beautifuldiscord --css $PWD/discord.css
    Found DiscordCanary under /usr/share/discord-canary
    Couldn't copy file ./node_modules/.bin/har-validator, no extracted directory
    Couldn't copy file ./node_modules/.bin/loose-envify, no extracted directory
    Couldn't copy file ./node_modules/.bin/mkdirp, no extracted directory
    Couldn't copy file ./node_modules/.bin/rimraf, no extracted directory
    Couldn't copy file ./node_modules/.bin/sshpk-conv, no extracted directory
    Couldn't copy file ./node_modules/.bin/sshpk-sign, no extracted directory
    Couldn't copy file ./node_modules/.bin/sshpk-verify, no extracted directory
    Couldn't copy file ./node_modules/.bin/uuid, no extracted directory
    Couldn't copy file ./node_modules/create-react-class/node_modules/.bin/loose-envify, no extracted directory
    Couldn't copy file ./node_modules/fbjs/node_modules/.bin/loose-envify, no extracted directory
    Couldn't copy file ./node_modules/http-signature/node_modules/.bin/sshpk-conv, no extracted directory
    Couldn't copy file ./node_modules/http-signature/node_modules/.bin/sshpk-sign, no extracted directory
    Couldn't copy file ./node_modules/http-signature/node_modules/.bin/sshpk-verify, no extracted directory
    Couldn't copy file ./node_modules/prop-types/node_modules/.bin/loose-envify, no extracted directory
    Couldn't copy file ./node_modules/react/node_modules/.bin/loose-envify, no extracted directory
    Couldn't copy file ./node_modules/react-dom/node_modules/.bin/loose-envify, no extracted directory
    Couldn't copy file ./node_modules/request/node_modules/.bin/har-validator, no extracted directory
    Couldn't copy file ./node_modules/request/node_modules/.bin/uuid, no extracted directory
    Traceback (most recent call last):
      File "/usr/local/bin/beautifuldiscord", line 11, in <module>
        load_entry_point('BeautifulDiscord==0.1.0', 'console_scripts', 'beautifuldiscord')()
      File "/usr/local/lib/python3.6/site-packages/beautifuldiscord/app.py", line 198, in main
        with open('./app/index.js', 'r', encoding='utf-8') as f:
    FileNotFoundError: [Errno 2] No such file or directory: './app/index.js'

Then, when attempting to use BD again immediately afterwards:

    cloud@CloudPuter:~/Software/BeautifulDiscord$ beautifuldiscord --css $PWD/discord.css
    Found DiscordCanary under /usr/share/discord-canary
    WARNING: app.asar not found
    Traceback (most recent call last):
      File "/usr/local/bin/beautifuldiscord", line 11, in <module>
        load_entry_point('BeautifulDiscord==0.1.0', 'console_scripts', 'beautifuldiscord')()
      File "/usr/local/lib/python3.6/site-packages/beautifuldiscord/app.py", line 198, in main
        with open('./app/index.js', 'r', encoding='utf-8') as f:
    FileNotFoundError: [Errno 2] No such file or directory: './app/index.js'

Looks like Inkx is using a Mac, so this problem doesn't appear to be platform-specific. The steps I detailed worked flawlessly on Canary 0.0.32. Unfortunately I have no idea how to go about fixing this.

**Comment by Rapptz** [comment]
This is a known issue and I am investigating.

**Comment by Rapptz** [comment]
I've gotten this fixed locally on Windows but I don't have easy access to other instances of Discord (e.g. Linux or macOS).

The gist of it is that they've moved their entry point for the main window over to a different place in an OTA (over the air) module. The idea is to inject it there instead after it's been extracted and the like.

One minor thing is having to make `--revert` work again. Ultimately speaking, this new directory layout does make the asar unpacking pretty much unnecessary so there'd have to be a rewrite to skip that step, at least on Windows.

**Comment by simoniz0r** [comment]
That's probably the best news I could have hoped for out of this, honestly.  So you're saying the files that you modify to apply CSS changes are no longer in the app.asar and nothing needs to be extracted for them to be applied?  That's pretty good news if so.

**Comment by InkxtheSquid** [comment]
I think it's in the bootstrap folder, in the discord_desktop_core.zip file, I see an app folder and a index.js and etc.

**Comment by simoniz0r** [comment]
Hmm, this may be good and bad news, then.  

The good news is that the entire contents of the app.asar now appear to be located in `~/.config/discordcanary/0.0.35/app`, so the asar no longer needs to be extracted to make modifications.

The bad news would be that I'm willing to bet that this directory will be cleared out every time that updates are pushed from Discord's servers.  I'm thinking that this will probably happen.  They may have even done this to avoid people having issues between Discord version changes due to the app.asar being extracted.

**Comment by UraYukimitsu** [comment]
Hi, check out my fork, I got the fix working for Windows, Mac OS and Linux - not doing a pull request though as I added JS support. (Also please don't pay attention to the monstrous amount of commits I keep pushing without testing haha)

**Comment by simoniz0r** [comment]
I was able to get CSS working in Canary by adding the following to `~/.config/discordcanary/modules/discord_desktop_core/app/manScreen.js` : 

These variables are no longer present so need to be added: 
```
var _fs = require('fs');

var _fs2 = _interopRequireDefault(_fs);
```

Then I just replaced this function

```
  mainWindow.webContents.on('dom-ready', function () {});
```

with the function from BeautifulDiscord to load the CSS
```
  mainWindow.webContents.on('dom-ready', function () {
    mainWindow.webContents.executeJavaScript(
      _fs2.default.readFileSync('/home/simonizor/.config/discordcanary/cssInjection.js', 'utf-8')
    );
  });
```

**Comment by InkxtheSquid** [comment]
if that's the case @simoniz0r, then it could be the end of this css injector, if there's a way to fix this then we could have another chance, but at this rate I don't know.

**Comment by simoniz0r** [comment]
What do you mean @InkxtheSquid ?  I was able to add these changes and have the current CSS injector script from BeautifulDiscord work fine.

These changes might have to be reapplied whenever server side updates are applied, but that's still pretty simple to do.

**Comment by InkxtheSquid** [comment]
couldn't find a way on Mac yet

**Comment by Rapptz** [comment]
I pushed changes to `canary` branch (see here: https://github.com/leovoel/BeautifulDiscord/tree/canary).

I'll add Linux support later since it shouldn't be too difficult.

**Comment by simoniz0r** [comment]
Just FYI @Rapptz Discord Canary 0.0.36 reverts this change and BeautifulDiscord works with it again without the new changes in the `canary` branch.

**Comment by InkxtheSquid** [comment]
well time to close now :slightly_smiling_face:

**Comment by Rapptz** [comment]
@simoniz0r by the nature of canary things get reverted and re-applied multiple times so it's good to have the branch just in case.

**Comment by simoniz0r** [comment]
@Rapptz Changes are back, but seem worse this time.  I cannot find the
```
  mainWindow.webContents.on('dom-ready', function () {});
```
function to change anywhere so far.

**Comment by shikhir-arora** [comment]
He pushed a new fix just a bit ago, See here: https://github.com/leovoel/BeautifulDiscord/issues/38#issuecomment-352604592 and the new fix: https://github.com/leovoel/BeautifulDiscord/commit/cd04419d458d9910cceabeb45b0e19a8efb2dd77 --- try that and see if it works.

**Comment by simoniz0r** [comment]
I actually just figured out that that function doesn't need to be replaced at all anymore apparently.  I just added the variables that were missing before and the function for loading the CSS directly below this function.  I'm not sure if the placement is important, but that seemed like a good spot to put it lol.

```
    webContentsSend(mainWindow.isFocused() ? 'MAIN_WINDOW_FOCUS' : 'MAIN_WINDOW_BLUR');
    if (!lastPageLoadFailed) {
      connectionBackoff.succeed();
      splashScreen.pageReady();
    }
  });
```

**Comment by TheSqrtMinus1** [comment]
newest update to discord (stable!) seems to have reintroduced this

beautifuldiscord fails with `FileNotFoundError: [Errno 2] No such file or directory: './app/index.js'`

**Comment by leovoel** [comment]
did you update beautifuldiscord?

**Comment by TheSqrtMinus1** [comment]
fixed by updating, thanks! 

👍

**Comment by UraYukimitsu** [comment]
https://github.com/UraYukimitsu/DiscordBootstrap Shameless plug - this works too ;)

**Comment by InkxtheSquid** [comment]
issue happened again today, this time the client was rewritten I think. They claimed that they've **pushed out a test update to Canary that will be backwards-incompatible with our older webcode. Once we're done testing this update, we will revert the test updates, which can break your desktop client**

**Comment by UraYukimitsu** [comment]
The problem most likely comes fromm the fact that `require` is no longer callable from the client.

**Comment by InkxtheSquid** [comment]
seems like they reverted it, but I'd say we might see they will actually put that stuff in with another new feature as well, so whoever is still in the the version that made BeautifulDiscord not work with it may need to make a workaround it

**Comment by simoniz0r** [comment]
Pretty sure they've pushed it again as I can no longer get CSS hotloading to work with Canary.
