### ISSUE TITLE
Canary issue?

### ISSUE THREAD

**Issue by AlexFlipnote** [leovoel/BeautifulDiscord#38]
So I have tried to install BeautifulDiscord from the Canary branch, however it stopped to work today at **17. September 2017**. Here's an image of the error it output
![Image](https://i.alexflipnote.xyz/578266.png)

I have tested from both C:\ and G:\ (Just to make sure it's not different partition issue, but the same error displays regardless.

Here's an image of the folder it searches, noticed that **discord_desktop_core** is not located here. In case of wonder, I have tried to reinstall Discord Canary to check.
![Image2](https://i.alexflipnote.xyz/90f01a.png)

Thanks in advance
-- AlexFlipnote

**Comment by shikhir-arora** [comment]
Can confirm the same issue on OS X. Looks like Discord changed where the `app.asar` is.

```bash

➜  ~ beautifuldiscord --css theme.css
Found Discord Canary under /Applications/Discord Canary.app/Contents/MacOS
WARNING: app.asar not found

Done!

You may now edit your /Users/shikhirarora/theme.css file,
which will be reloaded whenever it's saved.

Relaunching Discord now...
```

**Comment by Rapptz** [comment]
The change was reverted so you shouldn't use that branch.

**Comment by shikhir-arora** [comment]
Hey @Rapptz -- appears to have come back as of the just latest update on canary.

```hs

[BUILD INFO] Release Channel: canary, Build Number: 8829, Version Hash: dc95517d7e4f4754019a1be9446c540829f37f4d 2017-12-18 19:09:32.517
```

 They just pushed another canary update and it seems to not work on macOS. I've tried reinstalling and using both the `canary` and `master` (regular) branch of BeautifulDiscord.


```bash
➜  ~ python3 -m beautifuldiscord --css theme.css 
0: Found Discord PTB
1: Found Discord Canary
Discord executable to use (number): 1
WARNING: app.asar not found
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/site-packages/beautifuldiscord/__main__.py", line 3, in <module>
    main()
  File "/usr/local/lib/python3.6/site-packages/beautifuldiscord/app.py", line 233, in main
    with open('./app/index.js', 'r', encoding='utf-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: './app/index.js'
```

```bash

➜ ~ beautifuldiscord --css theme.css
0: Found Discord Canary
1: Found Discord PTB
Discord executable to use (number): 0
Couldn't copy file ./node_modules/.bin/har-validator, no extracted directory
Couldn't copy file ./node_modules/.bin/loose-envify, no extracted directory
Couldn't copy file ./node_modules/.bin/mkdirp, no extracted directory
Couldn't copy file ./node_modules/.bin/rimraf, no extracted directory
Couldn't copy file ./node_modules/.bin/sshpk-conv, no extracted directory
Couldn't copy file ./node_modules/.bin/sshpk-sign, no extracted directory
Couldn't copy file ./node_modules/.bin/sshpk-verify, no extracted directory
Couldn't copy file ./node_modules/.bin/uuid, no extracted directory
Couldn't copy file ./node_modules/create-react-class/node_modules/.bin/loose-envify, no extracted directory
Couldn't copy file ./node_modules/fbjs/node_modules/.bin/loose-envify, no extracted directory
Couldn't copy file ./node_modules/http-signature/node_modules/.bin/sshpk-conv, no extracted directory
Couldn't copy file ./node_modules/http-signature/node_modules/.bin/sshpk-sign, no extracted directory
Couldn't copy file ./node_modules/http-signature/node_modules/.bin/sshpk-verify, no extracted directory
Couldn't copy file ./node_modules/prop-types/node_modules/.bin/loose-envify, no extracted directory
Couldn't copy file ./node_modules/react/node_modules/.bin/loose-envify, no extracted directory
Couldn't copy file ./node_modules/react-dom/node_modules/.bin/loose-envify, no extracted directory
Couldn't copy file ./node_modules/request/node_modules/.bin/har-validator, no extracted directory
Couldn't copy file ./node_modules/request/node_modules/.bin/uuid, no extracted directory
Traceback (most recent call last):
  File "/usr/local/bin/beautifuldiscord", line 11, in <module>
    load_entry_point('BeautifulDiscord==0.1.0', 'console_scripts', 'beautifuldiscord')()
  File "/usr/local/lib/python3.6/site-packages/beautifuldiscord/app.py", line 233, in main
    with open('./app/index.js', 'r', encoding='utf-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: './app/index.js'
```

**Comment by Rapptz** [comment]
That's not the `canary` branch (I no longer open any `index.js` file there. Make sure you're using the right branch.

**Comment by shikhir-arora** [comment]
Thanks for fixing it so fast/pointing that out, forgot to pull the right branch -- my mistake.
`python3 -m pip install -U https://github.com/leovoel/BeautifulDiscord/archive/canary.zip` worked fine. Appreciate the help.

**Comment by simoniz0r** [comment]
Seems like we hopefully have a more permanent change this time.  The folders that were in the `desktop_core_app` folder in the config directory have been moved into `core.asar`.  If `core.asar` is extracted into the `discord_desktop_core` directory, we get all of the same folders we had from last update and are able to apply the same changes.  Move core.asar to a backup location, and everything works pretty similarly to the way it did before all of these changes.  Slightly more convenient now as it won't require elevated permissions to modify.

**Comment by Rapptz** [comment]
Not exactly, since the `require` call is quite explicit with `require('./core.asar')`.

**Comment by simoniz0r** [comment]
I noticed that also and expected this to not work, but I had no troubles making the above modifications.  I extracted `core.asar` to `desktop_core_app`, added the necessary variables and function to hotload CSS, and moved `core.asar` to `core.asar.bak`.  After doing that, CSS hotloading works as expected.

**Comment by Rapptz** [comment]
![image](https://user-images.githubusercontent.com/1695103/34193411-914c43f8-e521-11e7-911a-2e61140e606e.png)

Like I said, not quite.

**Comment by simoniz0r** [comment]
When did you get that error?  I've been using the client  with the above modifications for a couple of hours now with no errors.  Might just be a thing that works on Linux?

**Comment by Rapptz** [comment]
Doesn't matter much -- I've already fixed it by just repacking the asar file when I finish modifying it.

I've also added preliminary Linux support based on what people have told me. If it works please let me know (or if it stops working) @simoniz0r

**Comment by simoniz0r** [comment]
@Rapptz Doesn't seem to be able to find the directory:

```
Found DiscordCanary under /opt/discord-canary
Traceback (most recent call last):
  File "./.local/bin/beautifuldiscord", line 11, in <module>
    load_entry_point('BeautifulDiscord==0.1.0', 'console_scripts', 'beautifuldiscord')()
  File "/home/simonizor/.local/lib/python3.6/site-packages/beautifuldiscord/app.py", line 211, in main
    os.chdir(discord.script_path)
  File "/home/simonizor/.local/lib/python3.6/site-packages/beautifuldiscord/app.py", line 92, in script_path
    raise RuntimeError('Could not find discord application version under "{}".'.format(config))
RuntimeError: Could not find discord application version under "/home/simonizor/.config/discordcanary".
```

**Comment by Rapptz** [comment]
You mind giving me the results of `os.listdir` of that path?

**Comment by simoniz0r** [comment]
I'm not very familiar with python, so hopefully I'm doing this correctly:
```
[ simonizor ~ ] python3 -c "os.listdir('/home/simonizor/.config/discordcanary/0.0.41')"                       
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'os' is not defined
```

**Comment by sansation** [comment]
```
~ ➜  python                                                           
Python 3.6.3 (default, Oct 24 2017, 14:48:20) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> os.listdir('/home/sans/.config/discordcanary/')
['blob_storage', 'discord-canary-2.png', 'QuotaManager', 'discord-canary-8.png', 'modules.log', 'discord-canary-6.png', 'Local Storage', 'discord-canary-10.png', 'Cache', 'discord-canary-9.png', 'tray-deafened.png', 'IndexedDB', '0.0.41', 'discord-canary-1.png', 'Cookies-journal', 'queued_analytics_events.json', 'discord-canary-5.png', 'tray.png', 'tray-speaking.png', 'QuotaManager-journal', 'settings.json', 'tray-connected.png', 'Preferences', 'tray-unread.png', 'discord-canary-4.png', 'Cookies', 'cssInjection.js', 'discord-canary-7.png', 'databases', 'discord-canary-0.png', 'tray-muted.png', 'discord-canary-11.png', 'discord-canary-3.png', 'GPUCache']
```

**Comment by shikhir-arora** [comment]
Can confirm it does work on macOS with the latest canary, albeit giving some `node_modules` warnings, which don't matter here. 

```hs
[BUILD INFO] Release Channel: canary, Build Number: 8933, Version Hash: 853d8a4b384a443599a4b9349ce7aaa10dbf8a26
2017-12-20 02:34:04.649 
```

```bash

➜  ~ python3 -m pip install -U https://github.com/leovoel/BeautifulDiscord/archive/canary.zip
Collecting https://github.com/leovoel/BeautifulDiscord/archive/canary.zip
  Downloading https://github.com/leovoel/BeautifulDiscord/archive/canary.zip
     \ 20kB 3.2MB/s
Requirement already up-to-date: psutil in /usr/local/lib/python3.6/site-packages (from BeautifulDiscord==0.1.0)
Installing collected packages: BeautifulDiscord
  Found existing installation: BeautifulDiscord 0.1.0
    Uninstalling BeautifulDiscord-0.1.0:
      Successfully uninstalled BeautifulDiscord-0.1.0
  Running setup.py install for BeautifulDiscord ... done
Successfully installed BeautifulDiscord-0.1.0

➜  ~ beautifuldiscord --css theme3.css
0: Found Discord Canary
1: Found Discord PTB
Discord executable to use (number): 0
Couldn't copy file ./node_modules/.bin/har-validator, no extracted directory
Couldn't copy file ./node_modules/.bin/loose-envify, no extracted directory
Couldn't copy file ./node_modules/.bin/mkdirp, no extracted directory
Couldn't copy file ./node_modules/.bin/rimraf, no extracted directory
Couldn't copy file ./node_modules/.bin/sshpk-conv, no extracted directory
Couldn't copy file ./node_modules/.bin/sshpk-sign, no extracted directory
Couldn't copy file ./node_modules/.bin/sshpk-verify, no extracted directory
Couldn't copy file ./node_modules/.bin/uuid, no extracted directory
Couldn't copy file ./node_modules/create-react-class/node_modules/.bin/loose-envify, no extracted directory
Couldn't copy file ./node_modules/fbjs/node_modules/.bin/loose-envify, no extracted directory
Couldn't copy file ./node_modules/http-signature/node_modules/.bin/sshpk-conv, no extracted directory
Couldn't copy file ./node_modules/http-signature/node_modules/.bin/sshpk-sign, no extracted directory
Couldn't copy file ./node_modules/http-signature/node_modules/.bin/sshpk-verify, no extracted directory
Couldn't copy file ./node_modules/prop-types/node_modules/.bin/loose-envify, no extracted directory
Couldn't copy file ./node_modules/react/node_modules/.bin/loose-envify, no extracted directory
Couldn't copy file ./node_modules/react-dom/node_modules/.bin/loose-envify, no extracted directory
Couldn't copy file ./node_modules/request/node_modules/.bin/har-validator, no extracted directory
Couldn't copy file ./node_modules/request/node_modules/.bin/uuid, no extracted directory

Done!

You may now edit your /Users/shikhirarora/theme3.css file,
which will be reloaded whenever it's saved.

```
Thanks @Rapptz 👍

**Comment by Rapptz** [comment]
@sansation Thanks!

I think it should be fixed now.

**Comment by sansation** [comment]
Yep, that issue is fixed now. The only problem is that since I'm on Arch, there's no way to easily apply the CSS. Before, I could use `sudo` and it would work fine, but now it gives an error because it tries to check in `/root/.config/discordcanary/` for the version.

**Comment by Rapptz** [comment]
Ideally you should no longer need root.

Since the only writing it's doing should reside strictly inside `~/.config` it should be fine w/o root.

**Comment by sansation** [comment]
```
~ ➜  beautifuldiscord --css discord.css
Found DiscordCanary under /opt/discord-canary
Couldn't copy file ./node_modules/.bin/har-validator, no extracted directory
Couldn't copy file ./node_modules/.bin/loose-envify, no extracted directory
Couldn't copy file ./node_modules/.bin/mkdirp, no extracted directory
Couldn't copy file ./node_modules/.bin/rimraf, no extracted directory
Couldn't copy file ./node_modules/.bin/sshpk-conv, no extracted directory
Couldn't copy file ./node_modules/.bin/sshpk-sign, no extracted directory
Couldn't copy file ./node_modules/.bin/sshpk-verify, no extracted directory
Couldn't copy file ./node_modules/.bin/uuid, no extracted directory
Couldn't copy file ./node_modules/create-react-class/node_modules/.bin/loose-envify, no extracted directory
Couldn't copy file ./node_modules/fbjs/node_modules/.bin/loose-envify, no extracted directory
Couldn't copy file ./node_modules/http-signature/node_modules/.bin/sshpk-conv, no extracted directory
Couldn't copy file ./node_modules/http-signature/node_modules/.bin/sshpk-sign, no extracted directory
Couldn't copy file ./node_modules/http-signature/node_modules/.bin/sshpk-verify, no extracted directory
Couldn't copy file ./node_modules/prop-types/node_modules/.bin/loose-envify, no extracted directory
Couldn't copy file ./node_modules/react/node_modules/.bin/loose-envify, no extracted directory
Couldn't copy file ./node_modules/react-dom/node_modules/.bin/loose-envify, no extracted directory
Couldn't copy file ./node_modules/request/node_modules/.bin/har-validator, no extracted directory
Couldn't copy file ./node_modules/request/node_modules/.bin/uuid, no extracted directory
Traceback (most recent call last):
  File "/usr/bin/beautifuldiscord", line 11, in <module>
    load_entry_point('BeautifulDiscord==0.1.0', 'console_scripts', 'beautifuldiscord')()
  File "/usr/lib/python3.6/site-packages/beautifuldiscord/app.py", line 301, in main
    with open(css_injection_path, 'w', encoding='utf-8') as f:
PermissionError: [Errno 13] Permission denied: '/opt/discord-canary/cssInjection.js'
```

**Comment by Rapptz** [comment]
I thought I moved that over to a home directory but I didn't. I'll make sure to fix.

**Comment by Rapptz** [comment]
Should be fixed now. It makes the file over to `~/.beautifuldiscord/cssInjection.js` instead of the old location.
