### ISSUE TITLE
Discord update broke the script

### ISSUE THREAD

**Issue by LWTechGaming** [leovoel/BeautifulDiscord#41]
From the looks of it, update 0.0.300 (Released today) has a different file structure and as such the script crashes when trying to find `index.js`.

Traceback:
```
Found Discord.exe under C:\Users\Linus\AppData\Local\Discord\app-0.0.300
Traceback (most recent call last):
  File "C:\Users\Linus\AppData\Local\Programs\Python\Python35-32\lib\runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Linus\AppData\Local\Programs\Python\Python35-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Linus\AppData\Local\Programs\Python\Python35-32\lib\site-packages\beautifuldiscord\__main__.py", line 3, in <module>
    main()
  File "C:\Users\Linus\AppData\Local\Programs\Python\Python35-32\lib\site-packages\beautifuldiscord\app.py", line 233, in main
    with open('./app/index.js', 'r', encoding='utf-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: './app/index.js'
```
Tested with the most recent version of BeautifulDiscord. The new file structure of the extracted `app` folder looks like this:
```
app_bootstrap/
common/
node_modules/
build_info.json
cssInjection.js
package.json`
```
Index.js appears to be in app_bootstrap.

**Comment by elenapan** [comment]
Having the same issue on Ubuntu 17.04, with Discord 0.0.4 that was released today.

```
Found Discord under /usr/share/discord
WARNING: app.asar not found
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/elena/Programs/BeautifulDiscord/beautifuldiscord/__main__.py", line 3, in <module>
    main()
  File "/home/elena/Programs/BeautifulDiscord/beautifuldiscord/app.py", line 198, in main
    with open('./app/index.js', 'r', encoding='utf-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: './app/index.js'
```

**Comment by Rapptz** [comment]
I merged the canary branch into the stable master branch so this should be fixed now.
