### ISSUE TITLE
No such file or directory: './app/index.js'

### ISSUE THREAD

**Issue by pavlukivan** [leovoel/BeautifulDiscord#46]
I'm using Discord PTB, I'm not sure if the changes are in stable version already. Basically the app is unable to find index.js

**Comment by Rapptz** [comment]
You are way out of date. Please update.

**Comment by pavlukivan** [comment]
It's the last version, I used the version from pip but just checked with the git version and the error is still there.

**Comment by pavlukivan** [comment]
I don't understand anything in the process of injection, but the only index.js file I could fine is app/app_bootstrap/index.js

**Comment by Rapptz** [comment]
There is no index.js injection point in the newest version. So I don't think you updated.

**Comment by pavlukivan** [comment]
```
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\pavlukivan>mkdir tmp

C:\Users\pavlukivan>cd tmp

C:\Users\pavlukivan\tmp>git clone https://github.com/leovoel/BeautifulDiscord.gi
t
Cloning into 'BeautifulDiscord'...
remote: Counting objects: 169, done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 169 (delta 3), reused 7 (delta 2), pack-reused 159
Receiving objects: 100% (169/169), 42.09 KiB | 0 bytes/s, done.
Resolving deltas: 100% (101/101), done.

C:\Users\pavlukivan\tmp>cd BeautifulDiscord

C:\Users\pavlukivan\tmp\BeautifulDiscord>dir
 Volume in drive C is Local Disk (:3)
 Volume Serial Number is 6C88-DBE7

 Directory of C:\Users\pavlukivan\tmp\BeautifulDiscord

16.02.2018  16:16    <DIR>          .
16.02.2018  16:16    <DIR>          ..
16.02.2018  16:16                32 .gitignore
16.02.2018  16:16    <DIR>          beautifuldiscord
16.02.2018  16:16             1 095 LICENSE
16.02.2018  16:16                62 MANIFEST.in
16.02.2018  16:16             2 938 README.md
16.02.2018  16:16                 8 requirements.txt
16.02.2018  16:16               620 setup.py
               6 File(s)          4 755 bytes
               3 Dir(s)  62 207 135 744 bytes free

C:\Users\pavlukivan\tmp\BeautifulDiscord>python beautifuldiscord
Found DiscordPTB.exe under C:\Users\pavlukivan\AppData\Local\DiscordPTB\app-0.0.
41
WARNING: app.asar not found
Traceback (most recent call last):
  File "C:\Python36-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Python36-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "beautifuldiscord\__main__.py", line 3, in <module>
  File "C:\Python36-32\lib\site-packages\beautifuldiscord\app.py", line 198, in
main
    with open('./app/index.js', 'r', encoding='utf-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: './app/index.js'

C:\Users\pavlukivan\tmp\BeautifulDiscord>
```

**Comment by pavlukivan** [comment]
Same with canary branch

**Comment by pavlukivan** [comment]
Never mind, just noticed the path. Thanks for the help.
