### ISSUE TITLE
Canary - error when trying to apply script

### ISSUE THREAD

**Issue by generalpask** [leovoel/BeautifulDiscord#50]
Getting this on Canary when trying to apply a script:

```
C:\Python\Python36-32>beautifuldiscord --css C:\Users\Nils\Dropbox\beautifuldiscord\styles\pask.css
Found DiscordCanary.exe under C:\Users\Nils\AppData\Local\DiscordCanary\app-0.0.204
WARNING: app.asar not found
Traceback (most recent call last):
  File "C:\Python\Python36-32\Scripts\beautifuldiscord-script.py", line 11, in <module>
    load_entry_point('BeautifulDiscord==0.1.0', 'console_scripts', 'beautifuldiscord')()
  File "C:\Python\Python36-32\lib\site-packages\beautifuldiscord\app.py", line 233, in main
    with open('./app/index.js', 'r', encoding='utf-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: './app/index.js'
```

**Comment by Rapptz** [comment]
Update before you open issues.

**Comment by generalpask** [comment]
@Rapptz Sorry about that. Was unaware of a new update being out.
