### ISSUE TITLE
Problem with Discord Flatpak installation

### ISSUE THREAD

**Issue by CramMK** [leovoel/BeautifulDiscord#86]
Hello! 
A similiar issues #62 was opened, but none of the tips helped on my installation.

Im getting this error:

ryzenlaptop ➜  ~/.config/discord beautifuldiscord --css my.css 
Found Discord under /app/discord
Traceback (most recent call last):
  File "/usr/local/bin/beautifuldiscord", line 11, in <module>
    load_entry_point('BeautifulDiscord==0.1.1', 'console_scripts', 'beautifuldiscord')()
  File "/usr/local/lib/python3.7/site-packages/beautifuldiscord/app.py", line 226, in main
    os.chdir(discord.script_path)
  File "/usr/local/lib/python3.7/site-packages/beautifuldiscord/app.py", line 92, in script_path
    raise RuntimeError('Could not find discord application version under "{}".'.format(config))
RuntimeError: Could not find discord application version under "/home/marc/.config/discord".

Also just calling beautifuldiscord didn't work

**Comment by SparrowOchon** [comment]
Try using the #65  the problem occurs because Flatpak doesn't use the same directory for applications. And Beautiful discord hard codes a path.

**Comment by lougehrig10** [comment]
I fixed the issue by changing ```'~/config/'``` on line 75 of app.py to ```~/.var/app/com.discordapp.Discord/config/'``` (XDG_CONFIG_HOME is not set for me) and I get the following error

```Found Discord under /app/discord

Done!

You may now edit your /home/gehrig/.var/app/com.discordapp.Discord/config/discord/0.0.10/modules/discord_desktop_core/discord-custom.css file,
which will be reloaded whenever it's saved.

Relaunching Discord now...
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/gehrig/.local/lib/python3.8/site-packages/beautifuldiscord/__main__.py", line 3, in <module>
    main()
  File "/home/gehrig/.local/lib/python3.8/site-packages/beautifuldiscord/app.py", line 388, in main
    discord.launch()
  File "/home/gehrig/.local/lib/python3.8/site-packages/beautifuldiscord/app.py", line 25, in launch
    subprocess.Popen([os.path.join(self.path, self.exe)], stdout=f, stderr=subprocess.STDOUT)
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
NotADirectoryError: [Errno 20] Not a directory: '/app/discord/Discord'
```

**Comment by CramMK** [comment]
I now removed Discord Flatpak and started using the rpmfusion package of discord
With that one, it works @lougehrig10
